# Generated by Django 4.1.2 on 2023-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otdelenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=60)),
                ('Dolshnost', models.CharField(max_length=60)),
                ('Otdelenie', models.CharField(max_length=60)),
                ('Telephon', models.TextField(max_length=150)),
                ('Pochta', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=60)),
                ('Dolshnost', models.CharField(max_length=60)),
                ('Otdelenie', models.CharField(max_length=60)),
                ('Telephon', models.TextField(max_length=150)),
                ('Pochta', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Upravlenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=60)),
                ('Dolshnost', models.CharField(max_length=60)),
                ('Otdelenie', models.CharField(max_length=60)),
                ('Telephon', models.TextField(max_length=150)),
                ('Pochta', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
