# Generated by Django 4.1 on 2022-10-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=40)),
                ('phone_type', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listpage.phonetype')),
            ],
        ),
    ]
